printWidth=92
tabWidth=4

[[overrides]]
files="*.{yml,yaml}"
[overrides.options]
tabWidth=2

[[overrides]]
files="*.html"
[overrides.options]
printWidth=108

[[overrides]]
files="web/templates/statement.html"
[overrides.options]
printWidth=128
