name: Code CI

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  code-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Black
        uses: psf/black@stable
        with:
          args: "./"
      - name: Prettier
        uses: creyD/prettier_action@v3.3
        with:
          prettier_options: --config ./.prettierrc.toml  --ignore-path ./.prettierignore --write .
          same_commit: true
          only_changed: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  py-test:
    runs-on: ubuntu-18.04
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres_password
        ports:
          - 5432:5432
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: APT install
        run: |
          sudo apt-get update
          sudo apt-get --yes install python3.7-dev libpq-dev
      - name: Install pipenv
        run: pip install pipenv
      - name: "Pipenv : Install dependecies"
        run: pipenv install -d
      - name: "Pipenv : Run test"
        run: pipenv run test
        env:
          SQL_DB_HOST: localhost
          SQL_DB_NAME: sms_impl
          SQL_DB_PASSWORD: postgres_password
